<a href="https://colab.research.google.com/github/daa103/DAA_ESAA/blob/main/HW(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#넘파이


> **넘파이개념**

*   Numpy=Nemerical Python 
*   빠른 배열의 연산속도 보장
*   C/C++ 같은 저수준 언어 기반의 호환 API제공
*  다양한 데이터 핸들링기능 제공

> **넘파이ndarray 개요**

* np.array(): ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray 반환
* ndarray.shape: ndarray의 차원과 크기를 튜플로 나타내줌
* ndarray.ndim: 각 array의 차원을 확인



 







In [ ]:
import numpy as np
 
array1= np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2=np.array([[1,2,3],[2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3=np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1:1차원, array2:2차원, array3: 2차원


> **ndarray의 데이터 타입**

* ndarray내 데이터값: 숫자값, 문자열값, 불값 가능
* 데이터 타입은 같은 데이터타입만 가능
* 데이터타입은 dtype속성으로 확인 가능
* 다른 데이터타입이 섞여있을때 더 큰 데이터타입으로 변환
* ndarray내 데이터값 타입 변경: astype() 이용

In [ ]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


> **ndarray 편리하게 생성-arange,zeros,ones**

* ndarray를 연속값이나 0또는 1로 초기화해서 쉽게 생성할때 사용
* arrange() :0부터 함수값-1까지 변환
* zeros() : 튜플형태의 shape를 입력하면 0으로 채운 shape의 ndarray로 반환
* ones() : 1로채운 ndarray로 반환환


In [ ]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


>**ndarray의 차원과 크기를 변경하는 reshape()**

* reshape()는 ndarray를 특정차원과 크기로 변환
* 인자로 -1을 적용하는경우 ndarray와 호환되는 새로운 shape로 변환

In [ ]:
array1=np.arange(10)
print('array1:/n', array1)

array2=array1.reshape(2,5)
print('array2:/n',array2)

array3=array1.reshape(5,2)
print('array3:/n',array3)

array1:/n [0 1 2 3 4 5 6 7 8 9]
array2:/n [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:/n [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:',array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:/n',array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:/n',array5.tolist())
print('array5 shape:',array5.shape)
#1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6:/n',array6.tolist())
print('array6:/n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:/n [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:/n [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:/n [[0], [1], [2], [3], [4], [5], [6], [7]]
array6:/n [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


>**넘파이의 ndarray의 데이터세트 선택하기-인덱싱**

####1. 단일값 추출

In [ ]:
#1부터 9까지 1차원 ndarray생성
array1=np.arange(start=1,stop=10)
print('array1:',array1)
#index는 0부터 시작하므로 array1[2]는 3번째 인덱스위치의 데이터 의미
value=array1[2]
print('value:',value)
print(type(value))

#다차원 ndarray에서 단일값 추출
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0)index 가리키는값:', array2d[0,0])
print('(row=0, col=1)index 가리키는값:', array2d[0,1])
print('(row=1, col=0)index 가리키는값:', array2d[1,0])
print('(row=2, col=2)index 가리키는값:', array2d[2,2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0)index 가리키는값: 1
(row=0, col=1)index 가리키는값: 2
(row=1, col=0)index 가리키는값: 4
(row=2, col=2)index 가리키는값: 9


####2. 슬라이싱
:기호를 이용하여 연속 데이터 슬라이싱하여 추출출

In [ ]:
array1=np.arange(start=1,stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

#2차원 ndarray에서 슬라이싱하기
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2,0:2]\n',array2d[0:2,0:2])
print('array2d[1:3,0:3]\n',array2d[1:3,0:3])
print('array2d[1:3,:]\n',array2d[1:3,:])
print('array2d[:,:]\n',array2d[:,:])

[1 2 3]
<class 'numpy.ndarray'>
array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


####3. 팬시인덱싱
:인덱스 집합 지정후 ndarray를 반환하는 인덱싱 방법법

In [ ]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2]=>',array3.tolist())
array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>',array4.tolist())
array5=array2d[[0,1]]
print('array2d[[0,1]]=>',array5.tolist())



array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


####4. 불린 인덱싱
:for loop/ if else보다 간단한 구현현

In [ ]:
array1d= np.arange(start=1,stop=10)
#[]안에  array1d>5 Boolean indexing을 적용
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱결과값:',array3)

boolean_indexes=np.array([False,False,False,False,False,True,True,True,True])
array3=array1d[boolean_indexes]
print('불린인덱스로 필터링결과:',array3)

indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링결과:',array4)

array1d>5 불린 인덱싱결과값: [6 7 8 9]
불린인덱스로 필터링결과: [6 7 8 9]
일반 인덱스로 필터링결과: [6 7 8 9]


>**행렬 정렬**
* sort()


In [ ]:
org_array=np.array([3,1,9,5])
print('원본 행렬:',org_array)
#np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort()호출 후 원본 행렬:',org_array)
#ndarray.sort()로 정렬
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:',sort_array2)
print('org_array.sort() 호출 후 원본 행렬:',org_array)

#내림차순정렬은 [::-1] 정렬

sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort()호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]
내림차순으로 정렬: [9 5 3 1]


In [ ]:
#행렬이 2차원이상일때 axis축으로 로우방향, 칼럼방향으로 정렬
array2d=np.array([[8,12],[7,1]])
sort_array2d_axis0=np.sort(array2d,axis=0)
print('로우방향으로 정렬:\n',sort_array2d_axis0)
sort_array2d_axis1=np.sort(array2d,axis=1)
print('칼럼방향으로 정렬:\n',sort_array2d_axis1)

로우방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


> * argsort()

In [ ]:
#원본이 정렬되었을때 기존 원본행렬 원소에 대한 인덱스가 필요할때
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬시 원본 행렬의 인덱스:',sort_indices)

#내림차순으로 정렬시 np.argsort()[::-1]
org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬시 원본 행렬의 인덱스:',sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬시 원본 행렬의 인덱스: [2 3 0 1]


>**선형대수 연산-행렬내적과 전치행렬 구하기**
 * 행렬내적> np.dot()


In [ ]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])
dot_product=np.dot(A,B)
print('행렬 내적결과:\n',dot_product)

행렬 내적결과:
 [[ 58  64]
 [139 154]]


>* 전치 행렬 > transpose()

In [ ]:
A=np.array([[1,2],[3,4]])
transpose_mat=np.transpose(A)
print('A의 전치행렬:\n',transpose_mat)

A의 전치행렬:
 [[1 3]
 [2 4]]
