<a href="https://colab.research.google.com/github/daa103/DAA_ESAA/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D87_117p.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **사이킷런으로 시작하는 머신러닝**
### **1.사이킷런 소개와 특징**
* 가장쉽고 효율적인 개발 라이브러리리
* 파이썬스러운 API
* 머신러닝을위한 알고리즘, 편리한 프레임워크





In [23]:
pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [24]:
import sklearn
print(sklearn.__version__)

1.2.2


###**2.첫번째 머신러닝 만들기-붓꽃 품종 예측**
* 붓꽃데이터세트-꽃잎의 길이,너비, 꽃받침의 길이와 너비를 기반으로 꽃의 품종 예측
> 붓꽃데이터를 생성하는데 load_iris() 사용.
> ML알고리즘은 결정트리 알고리즘으로 DecisionTreeClassifier를 적용한다.
* 분류-대표적 지도학습
> 지도학습-학습을 위한 다양한 Feature과 분류 결정값인 label 데이터로 모델을 학습한 후, 예측하는 방식 
> * sklearn.datasets-사이킷런에서 자체제공하는 데이터 세트를 생성하는 모듈의 모임
> * sklearn.tree-트리 기반 ML알고리즘 구현한 클래스
> * sklearn.model_selection-데이터를 학습, 검증, 예측으로 분리하거나 평가하기위한 다양한 모듈의 모임
> * 하이퍼 파라미터-알고리즘별 최적학습을위해 직접 입력하는 파라미터들을 통칭한다.
> * train_test_split()- 데이터세트를 학습데이터와 테스트데이터로 분리

In [25]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [26]:
#feature들과 data 구성확인을 위해 dataframe으로 변환
import pandas as pd

#붓꽃데이터세트로딩
iris=load_iris()

#iris.data는 iris 데이터세트에서 feature로 된 데이터를 numpy로 가지고있다.
iris_data=iris.data

#iris.target은 붓꽃데이터 세트에서 레이블 데이터를 numpy로 가지고있다.
iris_label=iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

#붓꽃 데이터 세트를 자세히 보기위해 DataFrame으로 변환한다.
iris_df=pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

1. 데이터세트는 학습용, 테스트용으로 분리
* train_test_split() 학습데이터와 테스트 데이터를 test_size 파라미터 입력값의 비율로 분할할

In [27]:
#test_size는 전체 데이터세트중 테스트 데이터 세트의 비율이다
#random_state는 호출시 같은 데이터생성을 위해 할당
X_train, X_test, y_train, y_test= train_test_split(iris_data, iris_label, test_size=0.2,random_state=11)

2. ML알고리즘으로 모델학습
*  DecisionTreeClassifier 의사결정트리클래스를 객체로 생성
* fit()매서드에 학습용 피처데이터속성과 결정값 데이터세트를 호출하여 데이터 학습

In [28]:
# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

# 학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

3. 예측수행
* ML모델을 이용해 데이터분류를 예측
* 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터세트로 예측 수행

In [29]:
pred=dt_clf.predict(X_test)

4. 예측 결과를 기반으로 의사결정트리의 예측성능평가
* 정확도: 예측결과가 실제 레이블값과 얼마나 맞는지 평가 
* accuracy_score() 함수는 첫번째 파라미터로 실제 레이블 데이터세트, 두번재 파라미터로 예측 레이블 데이터 세트 입력력

In [30]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:4f}'.format(accuracy_score(y_test,pred)))


예측 정확도: 0.933333


### **3. 사이킷런의 기반 프레임워크 익히기**
> #### Estimator이해 및 fit(),predict()메서드
* fit() : 모델학습을 위해
* predict() : 학습된 모델의 예측을 위해
* 지도학습 분류알고리즘을 구현한 클래스: Classifier
* 지도학습 회귀알고리즘을 구현한 클래스: Regressor
* 모든알고리즘 구현한 클래스: Estimator
* 비지도학습은 차원축소, 클러스터링, 피처추출
>>* fit(): 입력데이터형태에 맞추어 데이터변환을 위해 사전구조를 맞춘다
>>* transform(): 입력데이터의 차원변환, 클러스터링, 피처추출등의 작업
>>* fit_transform(): fit과 transform을 결합

>#### 사이킷런 주요모듈
* 예제데이터
>> sklearn.dattasets: 사이킷런에 내장되어 예제제공
*피처처리
>> * sklearn.preprocessing :데이터 전처리에 필요한 가공기능제공(문자를 숫자형으로, 정규화...)
 * sklearn.feature_selection: 알고리즘에 영향을 미치는 피처를 우선순위대로 셀렉션 작업을 수행하는 다양한 기능 제공
 * sklearn.feature_extraction: 텍스트 데이터나 이미지 벡터화된 피처를 추출하는데 사용
* 피처처리& 차원축수
>> sklearn.decomposition: 차원 축소관련 알고리즘 지원 모듈. 
* 데이터분리, 검증, 파라미터튜닝
>> sklearn.model_selection: 교차검증을 위한 학습용/테스트용 분리. 
* 평가
>> sklearn.metrics: 분류,회귀,클러스터링,페어와이즈에 대한 다양한 성능 측정 방법 제공
* ML알고리즘
>> * sklearn.ensemble: 앙상블알고리즘
>>* sklearn.linear_model :주로 선혀으 회귀,릿지,랏소 및 로지스틱회귀 등 회귀관련알고리즘제공
>>* sklearn.naive_baybes :나이브베이즈 알고리즘제공
>>* sklearn.neighbors : 최근접 이웃알고리즘 제공
>>* sklearn.svm: 서포트벡터 머신 알고리즘 제공
>>* sklearn.tree: 의사결정 트리 알고리즘 제공
>>* sklearn.cluster : 비지도 클러스터링 알고리즘 제공
* 유틸리티
>>* sklearn.pipeline: 피처처리등의 변환과 ML알고리즘 학습, 예측을 함께 묶어서 실행하는 유틸리티 제공
> #### 내장된 예제 데이터세트
* 분류와 회귀연습하기위한세트
>> * datasets.load_boston() :회귀용도
>> * datasets.load_breast_cancer() :분류용도
>> * datasets_load_diabetes() :회귀용도
>> * datasets.load_digits() :분류용도
>> * datasets.loda_iris() :분류용도
* fetch계열의 명령은 데이터가커서 인터넷에서 내려받아 scikit_learn_Data라는 서브디렉토리에 저장 후 불러들이는 데이터

* 분류와 클러스터링을 위한 표본 데이터 생성기
> * datasets.make_classifications() : 분류를 위한 데이터세트를 만든다.
> * datasets.make_blobs() : 클러스터링을 위한 데이터세트를 무작위로 생성
* 키의 구성
>* data : 피처의 데이터 세트
>* target : 분류 시 레이블값, 회귀일 때는 숫자 결괏값 데이터 세트
>* target_names : 개별 레이블의 이름
>* feature_names : 피처의 이름
>* DESCR : 데이터 세트에 대한 설명과 각 피처설명명


In [31]:
from sklearn.datasets import load_iris

iris_data=load_iris()
print(type(iris_data))
#Bunch클래스는 파이썬 딕셔너리 자료형과 유사사

<class 'sklearn.utils._bunch.Bunch'>


In [32]:
keys=iris_data.keys()
print('붓꽃 데이터 세트의 키들:',keys)
#데이터키는 피처들의 데이터값을 가리킨다.

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [33]:
print('\n feature_names의 type:',type(iris_data.feature_names))
print(' feature_names의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type:', type(iris_data.target_names))
print(' target_names의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

print('\n data의 type:', type(iris_data.data))
print(' data의 shpae:', iris_data.data.shape)
print(iris_data['data'])

print('\n target의 type:', type(iris_data.target))
print(' target의 shpae:', iris_data.target.shape)
print(iris_data.target)


 feature_names의 type: <class 'list'>
 feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>
 target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
 data의 shpae: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5

###**Model selection모듈 소개**
학습데이터와 테스트데이터를 분리하거나 교차검증 분할 및 평가, 그리고 estimator의 하이퍼 파라미터를 튜닝하기 위한 함수와 클래스를 제공
>#### 학습/테스트 데이터세트분리-train_test_split()


In [34]:
#테스트 데이터세트를 이용하지 않고 학습데이터로만 예측하면 발생하는 문제 확인인
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris=load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label)

# 학습 데이터 세트으로 예측 수행
pred = dt_clf.predict(train_data)
print('예측 정확도:', accuracy_score(train_label, pred))

예측 정확도: 1.0


train_test_split()을 이용해 학습데이터세트와 테스트데이터세트로 분리를 해야한다.
sklearn.model_selection에서 train_test_split을 로드하고 피처데이터세트, 레이블데이터세트를 차례로 입력받는다. 
* test_size: 전체데이터에서 데이터세트 크기를 얼마로 설정할것인지 정한다
* shuffle: 데이터분리 전, 섞을지 결정하는데 사용된다. 디폴트는 true
* random_state: 호출시 동일한 데이터세트 생성

In [35]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf = DecisionTreeClassifier()
iris_data = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)
     
#학습데이터 기반으로 DecisionTreeClassifier를 학습하고 예측 정확도 측정정
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))
     

예측 정확도: 0.9556


> #### K폴드 교차검증
k개의 데이터폴드 세트를 만들어 k번만큼 각 폴트세트에 학습과 검증평가를 반복적으로 수행하는 방법
* 데이터세트 k등분->K-1개는 학습데이터, 마지막은 검증데이터세트로설정->점진적으로 하나씩 변경하며 학습과 평가를한다->K개의 예측 평가 평균
* 사이킷런에선 KFold와 StratifiedKFold클래스 제공

In [36]:
# KFold(n_splits=K)로 KFold객체 생성
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris=load_iris()
features=iris.data
label=iris.target
dt_clf=DecisionTreeClassifier(random_state=156)

# 5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150


In [37]:
#KFold객체의 split()을 호출해 교차검증 수행시마다 예측정확도 측정
n_iter=0

# KFold 객체의 split()를 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):
  # kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  # 학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)
  n_iter += 1
  # 반복 시마다 정확도 측정
  accuracy = np.round(accuracy_score(y_test, pred), 4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print('\n#{0} 교차 검증 정확도 : {1}, 학습 데이터 크기 : {2}, 검증 데이터 크기 : {3}'.format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스 : {1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

# 개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도 : 1.0, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#1 검증 세트 인덱스 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 : 0.9667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#2 검증 세트 인덱스 : [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 : 0.8667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#3 검증 세트 인덱스 : [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 : 0.9333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#4 검증 세트 인덱스 : [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 : 0.7333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#5 검증 세트 인덱스 : [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


>##### Stratified K폴드
:불균형한 분포도를 가진 레이블 데이터집합을위한 K폴드 방식
* K폴드가 레이블데이터 집합이 원본데이터 집합의 레이블 분포를 학습 및 테스트세트에 제대로 분배하지 못하는 경우의 문제 해결


In [38]:
#붓꽃 데이터세트를 DataFrame으로 생성하고 레이블 값의 분포도 확인
import pandas as pd

iris=load_iris()
iris_df= pd.DataFrame(data=iris.data, columns = iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [39]:
kfold = KFold(n_splits=3)
n_iter=0
for train_index, test_index in kfold.split(iris_df):
  n_iter += 1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print('## 교차 검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n', label_train.value_counts())
  print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    50
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    50
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    50
Name: label, dtype: int64


교차검증마다 3개의 폴드 세트로 만들어지는 학습레이블과 검증레이블이 완전히 다른값으로 추출
->예측 정확도가 0이되는 상황 발생
* StratifiedKFold는 KFold로 분할된 레이블데이터세트가 전체 레이블값 분포도를 반영하지 못하는 문제를 해결해준다. 
* StratifiedKFold는 KFold와 달리 레이블데이터분포도에 따라 학습/검정 데이터를 나누기 때문에 split()메서드에 인자로 피처데이터세트 뿐만아니라 레이블데이터세트도 필요하다.

In [40]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter=0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
  n_iter += 1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print('## 교차 검증 : {0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n', label_train.value_counts())
  print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증 : 1
학습 레이블 데이터 분포:
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
1    17
2    16
Name: label, dtype: int64
## 교차 검증 : 2
학습 레이블 데이터 분포:
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
2    17
1    16
Name: label, dtype: int64
## 교차 검증 : 3
학습 레이블 데이터 분포:
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
2    17
0    16
Name: label, dtype: int64


In [41]:
#StratifiedKFold를 이용해 데이터분리
dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

# StratifiedKFold의 split() 호출 시 반드시 레이블 데이터 세트도 추가 입력 필요
for train_index, test_index in skfold.split(features, label):
  # split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  # 학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)

  # 반복 시마다 정확도 측정
  n_iter += 1
  accuracy = np.round(accuracy_score(y_test,pred),4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print('\n#{0} 교차 검증 정확도 : {1}, 학습 데이터 크기 : {2}, 검증 데이터 크기 : {3}'.format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스 : {1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

print('\n## 교차 검증별 정확도:', np.round(cv_accuracy, 4))
print('## 평균 검증 정확도:',np.mean(cv_accuracy))


#1 교차 검증 정확도 : 0.98, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#1 검증 세트 인덱스 : [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도 : 0.94, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#2 검증 세트 인덱스 : [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도 : 0.98, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#3 검증 세트 인덱스 : [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도: 0.9666666666666667


분류에서의 교차검증은 K폴드가아니라 Stratified K폴드로 분할되어야한다. 회귀에서는 Stratified K폴드가 지원되지 않는다. 
>#### 교차검증을 보다간단하게-cross_val_score()
KFold 데이터를 학습하고 예측하는 코드를보면, 1. 폴드세트를 설정하고 2. for루프에서 반복으로 학습 및 테스트데이터의 인덱스를 추출한 뒤 3.반복적으로 학습과 예측을 수행하고 예측성능을 반환한다. 
**cross_val_score은 이런과정을 한번에 수행해주는 API**

* estimator는 사이킷런의 분류알고리즘 클래스인 Classifier 혹은 회귀알고리즘 클래스인 Regressor
* X: 피처데이터세트
* y: 레이블데이터세트
* scoring: 예측 성능평가지표
* cv: 교차검증 폴드수
* cross_val_score() 수행후 반환값은 scoring 파라미터로 지정된 성능 지표 측정값을 배열 형태로 반환
* cross_val_score() 는 calssifier가 입력되면 Stratified K폴드 방식으로 레이블값의 분포에 따라 학습, 데이터 세트를 분할한다.
* cross_validate()는 여러개 평가지표를 반환할 수 있고 학습데이터에 대한 성능평가지표와 수행시간도 같이 제공하는 API

In [42]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data=load_iris()
dt_clf=DecisionTreeClassifier(random_state=156)

data=iris_data.data
label=iris_data.target

#성능지표는 정확도 (accuracy), 교차검증세트는 3개
scores=cross_val_score(dt_clf,data,label,scoring='accuracy',cv=3)
print('교차 검증별 정확도:',np.round(scores,4))
print('평균 검증 정확도:',np.round(np.mean(scores),4))

#cross_val_score()는 cv로 지정된 횟수만큼 scoring 파라미터로 지정된 평가지표로
#평가 결괏값을 배열로 반환환

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


>#### GridSearchCV-교차검증과 최적 하이퍼 파라미터 튜닝을 한번에
* 하이퍼파라미터: 머신러닝 알고리즘을 구성하는 주요 구성요소이며 이 값을 조정해 알고리즘의 예측성능 개선
* 여러종류의 하이퍼파라미터를 테스트하면서 최적의 파라미터를 편리하게 찾게해준다.
>>* estimator: classifier, regressor, pipeline이 사용
>>* param_grid: key+리스트값을 가지는 딕셔너리가 주어진다. estimator튜닝을 위해 파라미터명과 여러 파라미터값을 지정
>>* scoring: 예측 성능을 ㅡㄱ정할 평가방법을 지정. 사이킷런의 성능 평가 지표를 지정하는 문자열로 지정하거나 별도의 성능평가 지표함수도 지정
>>* cv: 교차검증을위해 분할되는 학습/테스트세트의 개수
>>* refit: 디폴트가 True이며 true생성시 최적 하이퍼파라미터를 찾고 입력된 estimator객체를 해당 하이퍼파라미터로 재학습


In [43]:
#결정트리 알고리즘의 여러 하이퍼 파라미터를 
#순차적으로 변경하면서 파라미터 조합을 찾는 최적화 방법
grid_parameters={'max_depth':[1,2,3],'min_samples_split':[2,3]
                 }

In [46]:
# GridSearchCV API의 사용법
# 테스트할 하이퍼 파라미터세트는 딕셔너리형태로, 하이퍼 파라미터의 명칭은 문자열 key, 값은 리스트형
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# 데이터를 로딩하고 학습 데이터와 테스트 데이터 분리
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)

dtree = DecisionTreeClassifier()

### 파라미터를 딕셔너리 형태로 설정
parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}


In [47]:
#학습 데이터세트를 GridSearchCV객체의 fit 메서드에 인자로 입력
#cv_results_를 pandas의 dataframe으로 변환하여 주요칼럼만 발췌
 
import pandas as pd
#param_grid 하이퍼 파라미터를 3개의 train, test set fold로 나누어 테스트 수행 설정.
### refit=True가 디폴트. True면 가장 좋은 파라미터 설정으로 재학습
grid_dtree=GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)
#붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습,평가
grid_dtree.fit(X_train, y_train)

#GridSearchCV 결과를 추출해 DataFrame으로 변환
scores_df=pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

* params칼럼: 수행할때마다 적용된 개별 하이퍼 파라미터값
* rank_test_score는 하이퍼파라미터별로 성능이 좋은 score순위를 나타낸다. 
* mean_test_score는 개별하이퍼파라미터별로 CV의 폴딩 테스트 세트에 대해 총수행한 평가 평균값값

In [48]:
print('GridSearchCV 최적 파라미터:',grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:{0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:0.9750


refit=True(디폴트) : GridSearchCV가 최적 하이퍼 파라미터로 Estimator를 학습해 best_estimator_로 저장

In [49]:
# GridSearchCV의 refit으로 이미 학습된 estimator 반환
estimator = grid_dtree.best_estimator_

# GridSearchCV의 best_estimator_는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음
pred = estimator.predict(X_test)
print('테스트 데이터 세트 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

# 학습데이터를 GridSearchCV를 이용해 최적하이퍼 파라미터 튜닝을 수행한 뒤 별도의 테스트에서 평가가

테스트 데이터 세트 정확도: 0.9667
